#TERM = "xterm-256color"

[font]
size = 18

[font.normal]
family = "MesloLGS NF"

[window]
decorations = "Buttonless"
blur = true
opacity = 0.92
startup_mode = "Windowed"
dynamic_padding = true

[window.padding]
x = 12
y = 8

[window.dimensions]
columns = 96
lines = 48

[selection]
save_to_clipboard = true

[general]
live_config_reload = true
# themes from https://github.com/alacritty/alacritty-theme
# settings from https://alacritty.org/config-alacritty.html

import = ["~/.config/alacritty/themes/themes/material_theme_mod.toml"]
